# Generated by Django 3.2.15 on 2022-09-04 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default value', help_text='Give a short title to the note', max_length=100, verbose_name='Title')),
                ('text', models.TextField(help_text='Add more details', verbose_name='Body')),
                ('slug', models.SlugField(blank=True, help_text='Indicate the address for the note page. Use only Latin characters, numbers, hyphens and underscores', max_length=100, unique=True, verbose_name='Address for the page with a note')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
